In [1]:
import sys
import os

# Make project root visible
sys.path.append(os.path.abspath(".."))

import pandas as pd
from src.feature_extraction.audio_features import extract_features

# Correct dataset path
DATASET_PATH = os.path.abspath("../data/Coswara-Data")

print("Dataset path:", DATASET_PATH)
print("Exists:", os.path.exists(DATASET_PATH))

Dataset path: /Users/aadiii/Desktop/PulseIQ-AI/data/Coswara-Data
Exists: True

In [2]:
def get_counting_files():
    counting_files = []

    for root, dirs, files in os.walk(DATASET_PATH):
        for file in files:
            if file.endswith(".wav") and "counting" in file:
                full_path = os.path.join(root, file)
                counting_files.append(full_path)

    return counting_files


files = get_counting_files()

print(f"Total counting files: {len(files)}")

files[:5]

Total counting files: 5492

['/Users/aadiii/Desktop/PulseIQ-AI/data/Coswara-Data/20210816/20210816/9hXEs9OejdVxG6JJGCyKQpqVvy43/counting-normal.wav',
 '/Users/aadiii/Desktop/PulseIQ-AI/data/Coswara-Data/20210816/20210816/9hXEs9OejdVxG6JJGCyKQpqVvy43/counting-fast.wav',
 '/Users/aadiii/Desktop/PulseIQ-AI/data/Coswara-Data/20210816/20210816/o5T5M7lfD0aUpgHcFprqdICYcgd2/counting-normal.wav',
 '/Users/aadiii/Desktop/PulseIQ-AI/data/Coswara-Data/20210816/20210816/o5T5M7lfD0aUpgHcFprqdICYcgd2/counting-fast.wav',
 '/Users/aadiii/Desktop/PulseIQ-AI/data/Coswara-Data/20210816/20210816/ZPup16g7iWhU8qGhXNlgpgiN7ow2/counting-normal.wav']

In [3]:
dataset = []

for i, file in enumerate(files):
    try:
        features = extract_features(file)

        row = {
            "file": file,
            **features
        }

        dataset.append(row)

        if i % 100 == 0:
            print(f"Processed {i}/{len(files)} files")

    except Exception as e:
        continue

/Users/aadiii/Desktop/PulseIQ-AI/venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Processed 0/5492 files
Processed 100/5492 files
Processed 200/5492 files
Processed 300/5492 files
Processed 400/5492 files
Processed 500/5492 files
Processed 600/5492 files
Processed 700/5492 files
Processed 800/5492 files
Processed 900/5492 files
Processed 1000/5492 files
Processed 1100/5492 files
Processed 1200/5492 files
Processed 1300/5492 files
Processed 1400/5492 files
Processed 1500/5492 files
Processed 1600/5492 files
Processed 1700/5492 files
Processed 1800/5492 files
Processed 1900/5492 files
Processed 2000/5492 files

/Users/aadiii/Desktop/PulseIQ-AI/venv/lib/python3.12/site-packages/librosa/feature/spectral.py:2148: UserWarning: Empty filters detected in mel frequency basis. Some channels will produce empty responses. Try increasing your sampling rate (and fmax) or reducing n_mels.
  mel_basis = filters.mel(sr=sr, n_fft=n_fft, **kwargs)

Processed 2100/5492 files
Processed 2200/5492 files
Processed 2300/5492 files
Processed 2400/5492 files
Processed 2500/5492 files
Processed 2600/5492 files
Processed 2700/5492 files
Processed 2800/5492 files
Processed 2900/5492 files
Processed 3000/5492 files
Processed 3100/5492 files
Processed 3200/5492 files
Processed 3300/5492 files
Processed 3400/5492 files
Processed 3500/5492 files
Processed 3600/5492 files
Processed 3700/5492 files
Processed 3800/5492 files
Processed 3900/5492 files
Processed 4000/5492 files
Processed 4100/5492 files
Processed 4200/5492 files
Processed 4300/5492 files
Processed 4400/5492 files
Processed 4500/5492 files
Processed 4600/5492 files
Processed 4700/5492 files
Processed 4800/5492 files
Processed 4900/5492 files
Processed 5000/5492 files
Processed 5100/5492 files
Processed 5200/5492 files
Processed 5300/5492 files
Processed 5400/5492 files

In [4]:
len(dataset)

5411

In [5]:
df = pd.DataFrame(dataset)

df.head()

,file,pitch,spectral_centroid,zcr,jitter,shimmer,hnr,mfcc_1,mfcc_2,mfcc_3,mfcc_4,mfcc_5,mfcc_6,mfcc_7,mfcc_8,mfcc_9,mfcc_10,mfcc_11,mfcc_12,mfcc_13
0,/Users/aadiii/Desktop/PulseIQ-AI/data/Coswara-...,1311.654175,1799.875023,0.031378,0.021356,0.133057,12.828806,-428.889832,118.383751,23.473768,17.886021,15.640949,-15.971164,-21.472250,-10.734362,-11.321500,-13.427616,-11.184027,-7.961647,-7.676924
1,/Users/aadiii/Desktop/PulseIQ-AI/data/Coswara-...,1204.279907,1428.154074,0.029119,0.019582,0.109823,15.473836,-423.969360,108.888466,29.476095,8.485844,10.317966,-5.761888,-18.675251,-16.562550,-13.115095,-12.825630,-10.813223,-7.029854,-5.865900
2,/Users/aadiii/Desktop/PulseIQ-AI/data/Coswara-...,1336.240234,4383.912482,0.077219,0.023354,0.088631,17.858712,-448.266357,99.023499,27.736763,14.631805,23.619053,13.418217,-2.999132,1.750096,5.951513,-1.198462,-8.297428,-6.682642,-2.950694
3,/Users/aadiii/Desktop/PulseIQ-AI/data/Coswara-...,1504.194214,4021.171949,0.079062,0.019765,0.079095,18.108631,-406.470032,105.092224,16.298817,9.992468,26.291855,9.338547,-10.927941,-2.514927,2.074677,-7.480949,-11.926126,-6.714749,-4.547808
4,/Users/aadiii/Desktop/PulseIQ-AI/data/Coswara-...,1649.551025,2166.407122,0.069087,0.016123,0.112984,15.364097,-454.148224,111.118744,-3.170340,18.931486,16.839968,-7.684074,-8.459986,-21.481264,-12.294534,3.653708,-5.710431,-2.271479,-1.403067

In [6]:
os.makedirs("../data/voice_features", exist_ok=True)

df.to_csv("../data/voice_features/voice_dataset.csv", index=False)

print("Dataset saved!")

Dataset saved!

In [7]:
metadata = pd.read_csv("../data/Coswara-Data/combined_data.csv")

print(metadata.shape)
metadata.head()

(2746, 36)

,id,a,covid_status,record_date,ep,g,l_c,l_l,l_s,rU,...,vacc,bd,others_resp,ftg,st,ihd,asthma,others_preexist,cld,pneumonia
0,iV3Db6t1T8b7c5HQY2TwxIhjbzD3,28,healthy,2020-04-23,y,male,India,Anantapur,Andhra Pradesh,n,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AxuYWBN0jFVLINCBqIW5aZmGCdu1,25,healthy,2020-04-20,y,male,India,BENGALURU URBAN,Karnataka,n,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,C5eIsssb9GSkaAgIfsHMHeR6fSh1,28,healthy,2020-04-24,y,female,United States,Pittsburgh,Pennsylvania,n,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,YjbEAECMBIaZKyfqOvWy5DDImUb2,26,healthy,2020-04-23,y,male,India,Bangalore,Karnataka,n,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,aGOvk4ji0cVqIzCs1jHnzlw2UEy2,32,healthy,2020-04-22,y,male,India,Nalanda,Bihar,n,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
def extract_user_id(file_path):
    return file_path.split("/")[-2]


# test
df["user_id"] = df["file"].apply(extract_user_id)

df[["file", "user_id"]].head()

,file,user_id
0,/Users/aadiii/Desktop/PulseIQ-AI/data/Coswara-...,9hXEs9OejdVxG6JJGCyKQpqVvy43
1,/Users/aadiii/Desktop/PulseIQ-AI/data/Coswara-...,9hXEs9OejdVxG6JJGCyKQpqVvy43
2,/Users/aadiii/Desktop/PulseIQ-AI/data/Coswara-...,o5T5M7lfD0aUpgHcFprqdICYcgd2
3,/Users/aadiii/Desktop/PulseIQ-AI/data/Coswara-...,o5T5M7lfD0aUpgHcFprqdICYcgd2
4,/Users/aadiii/Desktop/PulseIQ-AI/data/Coswara-...,ZPup16g7iWhU8qGhXNlgpgiN7ow2

In [9]:
# Merge dataset with metadata on user_id
df = df.merge(metadata, left_on="user_id", right_on="id", how="left")

# Check result
df[["user_id", "covid_status"]].head()

                        user_id             covid_status
0  9hXEs9OejdVxG6JJGCyKQpqVvy43        positive_moderate
1  9hXEs9OejdVxG6JJGCyKQpqVvy43        positive_moderate
2  o5T5M7lfD0aUpgHcFprqdICYcgd2           recovered_full
3  o5T5M7lfD0aUpgHcFprqdICYcgd2           recovered_full
4  ZPup16g7iWhU8qGhXNlgpgiN7ow2  no_resp_illness_exposed

In [10]:
df["covid_status"].value_counts()

covid_status
healthy                        2813
positive_mild                   850
no_resp_illness_exposed         494
positive_moderate               328
resp_illness_not_identified     308
recovered_full                  290
positive_asymp                  176
under_validation                152
Name: count, dtype: int64

In [11]:
# Keep only required columns

columns_to_keep = ["file", "user_id", "covid_status"] + [
    col for col in df.columns if col.startswith("mfcc_") or col in [
        "pitch", "spectral_centroid", "zcr", "jitter", "shimmer", "hnr"
    ]
]

df_clean = df[columns_to_keep]

df_clean.head()

,file,user_id,covid_status,pitch,spectral_centroid,zcr,jitter,shimmer,hnr,mfcc_1,...,mfcc_4,mfcc_5,mfcc_6,mfcc_7,mfcc_8,mfcc_9,mfcc_10,mfcc_11,mfcc_12,mfcc_13
0,/Users/aadiii/Desktop/PulseIQ-AI/data/Coswara-...,9hXEs9OejdVxG6JJGCyKQpqVvy43,positive_moderate,1311.654175,1799.875023,0.031378,0.021356,0.133057,12.828806,-428.889832,...,17.886021,15.640949,-15.971164,-21.472250,-10.734362,-11.321500,-13.427616,-11.184027,-7.961647,-7.676924
1,/Users/aadiii/Desktop/PulseIQ-AI/data/Coswara-...,9hXEs9OejdVxG6JJGCyKQpqVvy43,positive_moderate,1204.279907,1428.154074,0.029119,0.019582,0.109823,15.473836,-423.969360,...,8.485844,10.317966,-5.761888,-18.675251,-16.562550,-13.115095,-12.825630,-10.813223,-7.029854,-5.865900
2,/Users/aadiii/Desktop/PulseIQ-AI/data/Coswara-...,o5T5M7lfD0aUpgHcFprqdICYcgd2,recovered_full,1336.240234,4383.912482,0.077219,0.023354,0.088631,17.858712,-448.266357,...,14.631805,23.619053,13.418217,-2.999132,1.750096,5.951513,-1.198462,-8.297428,-6.682642,-2.950694
3,/Users/aadiii/Desktop/PulseIQ-AI/data/Coswara-...,o5T5M7lfD0aUpgHcFprqdICYcgd2,recovered_full,1504.194214,4021.171949,0.079062,0.019765,0.079095,18.108631,-406.470032,...,9.992468,26.291855,9.338547,-10.927941,-2.514927,2.074677,-7.480949,-11.926126,-6.714749,-4.547808
4,/Users/aadiii/Desktop/PulseIQ-AI/data/Coswara-...,ZPup16g7iWhU8qGhXNlgpgiN7ow2,no_resp_illness_exposed,1649.551025,2166.407122,0.069087,0.016123,0.112984,15.364097,-454.148224,...,18.931486,16.839968,-7.684074,-8.459986,-21.481264,-12.294534,3.653708,-5.710431,-2.271479,-1.403067

In [12]:
df_clean.to_csv("../data/voice_features/voice_dataset_labeled.csv", index=False)

print("Final labeled dataset saved!")

Final labeled dataset saved!

In [13]:
def map_label(status):
    if status == "healthy":
        return 0
    else:
        return 1


df_clean["label"] = df_clean["covid_status"].apply(map_label)

df_clean["label"].value_counts()

label
0    2813
1    2598
Name: count, dtype: int64

In [14]:
df_clean.to_csv("../data/voice_features/voice_dataset_labeled.csv", index=False)

print("Final labeled dataset saved!")

Final labeled dataset saved!

In [15]:
df_clean.to_csv("../data/voice_features/voice_dataset_labeled_full.csv", index=False)

print("Full dataset saved!")

Full dataset saved!